#!/usr/bin/env bash

# set the report we want to grab
REPORT="Item_Inventories"

SCP="$(which scp)"

# currently can't do anything w/o scp
if [ -z $SCP ]
then
  echo "$0 requires scp to work!"
  exit 2
fi

# definitely need an OCLC symbol to do anything
if [ -z $OCLC_SYMBOL ]
then
  echo "$0 requires the environment variable OCLC_SYMBOL be set"
  exit 2
fi

# store the reports in the current directory if one isn't provided
if [ -z $REPORTS_PATH ]
then
  REPORTS_PATH="$PWD"
fi

# passing/setting DATE overrides getting the reports for 'today'
# (useful for debugging or getting older reports)
if [ -z $DATE ]
then
  DATE="$(date +"%Y%m%d")"
fi

# we'll need a lowercase version of the OCLC symbol to use as our user
# in the connection to scp.oclc.org
SYMBOL_LOWER=$(echo "$OCLC_SYMBOL" | awk '{print tolower($0)}')

# and we want an uppercase symbol as our file's prefix
if [[ $SYMBOL_LOWER -eq $OCLC_SYMBOL ]]
then
  OCLC_SYMBOL=$(echo "$SYMBOL_LOWER" | awk '{print toupper($0)}')
fi

OCLC_SERVER="$SYMBOL_LOWER@scp.oclc.org"
OCLC_PATH_ADD_DEL="wms/reports/$OCLC_SYMBOL*.$REPORT.$DATE.txt"

CMD="$SCP $OCLC_SERVER:$OCLC_PATH_ADD_DEL $REPORTS_PATH"

if [[ -z $DEBUG && $DEBUG -lt 1 ]]
then
  $CMD
else
  echo $CMD
fi
